import pytest
from alembic.util.exc import AutogenerateDiffsDetected
from conftest import disposable_database, migration_config
from sqlalchemy import inspect, text
from sqlalchemy.orm import Session

from alembic import command
from app.db.seed import seed_demo_data

pytestmark = pytest.mark.integration


def test_empty_database_upgrade_downgrade_upgrade(admin_engine):
    with disposable_database(admin_engine) as engine:
        with engine.begin() as connection:
            assert not inspect(connection).get_table_names()
            assert (
                connection.scalar(
                    text("SELECT count(*) FROM pg_extension WHERE extname = 'postgis'")
                )
                == 0
            )
            command.upgrade(migration_config(connection), "head")
            assert (
                connection.scalar(text("SELECT version_num FROM alembic_version"))
                == "0001_core_schema"
            )
            assert {"users", "projects", "sites", "site_metrics"} <= set(
                inspect(connection).get_table_names()
            )
            assert connection.scalar(text("SELECT PostGIS_Version()"))
            # Alembic must discover all models and report no migration/model drift.
            command.check(migration_config(connection))
            with Session(bind=connection) as session:
                assert seed_demo_data(session)["site_metrics"] == 24
                session.commit()

        with engine.begin() as connection:
            command.downgrade(migration_config(connection), "base")
            assert not (
                {"users", "projects", "sites", "site_metrics"}
                & set(inspect(connection).get_table_names())
            )
            assert (
                connection.scalar(text("SELECT to_regprocedure('darukaa_touch_updated_at()')"))
                is None
            )
            assert connection.scalar(text("SELECT count(*) FROM alembic_version")) == 0
            assert connection.scalar(text("SELECT PostGIS_Version()"))

        with engine.begin() as connection:
            command.upgrade(migration_config(connection), "head")
            command.check(migration_config(connection))
            assert (
                connection.scalar(text("SELECT version_num FROM alembic_version"))
                == "0001_core_schema"
            )


def test_extended_postgis_search_path_preserves_public_drift_detection(admin_engine):
    with disposable_database(admin_engine) as engine, engine.begin() as connection:
        command.upgrade(migration_config(connection), "head")
        connection.execute(text("CREATE EXTENSION fuzzystrmatch"))
        connection.execute(text("CREATE EXTENSION postgis_tiger_geocoder"))
        connection.execute(text("SET LOCAL search_path TO public, tiger"))
        assert "geocode_settings" in inspect(connection).get_table_names()
        command.check(migration_config(connection))
        assert connection.scalar(text("SELECT to_regclass('tiger.geocode_settings')"))
        connection.execute(text("CREATE TABLE public.module_02_drift_probe (id integer)"))
        with pytest.raises(AutogenerateDiffsDetected):
            command.check(migration_config(connection))
